긴 글 타자연습 동작 구현
msdio/Tamago pull request #142
Opened 2023-03-07 12:52 UTC by coolsmart2

## 📄 구현 내용 설명
- close #127 
- close #128
- close #129 
- close #130 
- close #132 
- 긴 글 단순 조회
- 긴 글에서 타자 연습 동작 구현
- 타자 연습시 정확도, wpm, 타속을 측정하여 화면에 출력
- Jest typescript 설정 후 간단한 정확도 wpm, 타속 테스트

### ⛱️ 주요 변경 사항
- jest.config.js로 ts-test 적용하여 test 파일 작동
  - 절대 경로 alias 작동하지 않아 설정
- page에 long페이지 추가 후 작업
- 저번 주에 보여드린 타수에 대해 더 정확한 로직으로 변경
  - 이전 로직은 Shift 같은 타수는 확인하지 못하지만 이런 특수키도 적용

### 🙋 이 부분을 리뷰해주세요
- components/practice/long/Typing/index.tsx에 거의 모든 로직이 섞여 있는데 keydown, onChange, useEffect 등으로 많은 이벤트에 의해 스파게티 코드가 되어 있다. 최대한 주석처리해서 설명하려고 노력했는데 이건 너무하다 싶은건 바로 이야기해주세요!
- 긴 글의 타자연습 url을 practice/long/[typingId]/[pageNum]?isTyping=true 로 되어 있는데 더 restful한 url이 있다면 말해주세요! 엄청 고민했지만 이거다 하는 url이 안 떠오르네요...
- 글쇠 분리를 일단 hangul-js를 통해 했지만 수미님이 만드신 글쇠 분리 메서드와 조금 다르게 동작하여 개발회의때 글쇠분리를 어디까지 할지 의논해야 될 것 같아요.
- wpm, 타속 관련해서는 조금씩 개선하는 방식으로 진행하겠습니다. -> backspace시 타속이 너무 많이 줄어들어서 고민해봐야할 것 같습니다.
- useEffect 사용시 의존성으로 useEffect에서 사용하는 모든 상태를 넣어야 eslint 경고가 사라지는데 원래 모든 상태를 의존성으로 넣는게 맞나요?
- 이전에 수미님이 getServerSideProps이 오류가 발생하신다고 해서 해봤는데 저는 되는 것 같네요.. 다만 typescript를 사용해서 타입 설정하는 것이 까다롭운 것 같습니다.

### 🤔 여기를 참고하면 도움이 돼요

- [how can i give type in getServerSideProps of Nextjs with typescript?](https://stackoverflow.com/questions/69559903/how-can-i-give-type-in-getserversideprops-of-nextjs-with-typescript)
- [getServerSideProps with TypeScript](https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#getserversideprops-with-typescript)

2023-03-07 17:50 UTC, msdio requested changes

2023-03-07 17:50 UTC, msdio commented on client/package.json
> +    "hangul-js": "^0.2.6",
수미님이 이전 pr에서 작성하신 constants 폴더의 hangul.ts 파일로 대체가 되지 않는 걸까요?

2023-03-07 17:50 UTC, msdio commented on client/src/components/header/index.tsx
> +          <Text onClick={handlePracticeLongClick}>긴글연습</Text>
@sumi-0011님이 라우트 핸들링 함수들 리팩토링 하실 때, 여기도 같이 해주세요!

2023-03-07 17:50 UTC, msdio commented on client/src/components/practice/long/Typing/InfoBar/InfoBarItem.tsx
> +const Wrapper = styled(Flex)`
굳이 이렇게 감쌀 이유가 있을까요? 그냥 두번째 Text에 border-left 속성을 주는게 더 깔끔하지 않을까 싶습니다

2023-03-07 17:50 UTC, msdio commented on client/src/components/practice/long/Typing/InfoBar/InfoBarItem.tsx
> +const Wrapper = styled(Flex)`
추가로 chakra ui에 Divider라는 컴포넌트가 있는데, 이걸 사용하면 보더 없이도 구현할 수 있을 것 같아요.

[Divider](https://chakra-ui.com/docs/components/divider)

2023-03-07 17:50 UTC, msdio commented on client/src/components/practice/long/Typing/index.tsx
> +  const [typingStates, setTypingStates] = useState<string>('f');
```suggestion
  const [typingStates, setTypingStates] = useState('f');
```
이것과 이 밑에 useState에 타입을 빼줘도 될 것 같아요.

2023-03-07 17:50 UTC, msdio commented on client/src/components/practice/long/Typing/index.tsx
> +  const currTypingCount = useRef<number>(0);
```suggestion
  const currTypingCount = useRef(0);
```

여기도 위에랑 마찬가지!

2023-03-07 17:50 UTC, msdio commented on client/src/components/practice/long/Typing/index.tsx
> +   * 의존성으로 왜 useEffect로 사용하는 상태를 모두 넣어야되는지 모르겠습니다.
useEffect의 의존성 배열에 사용하는 상태값을 모두 전달해줘야 하는 이유는 버그의 가능성 때문입니다. useEffect 훅은 의존성 배열에 있는 상태 값이 변경될 때마다 이펙트를 실행하는데, 내부의 사용되는 상태값 중 의존성 배열로 전달되지 않는 값이 생긴다면 원하는 시점에 업데이트 되지 않을 수 있어요.

애초에 리액트를 사용하는 사람들의 멘탈 모델이 `useEffect는 내부의 값이 변경될 때마다 다시 실행된다`라고 박혀있는 경우가 많이 때문에 의도치 않은 버그 방지를 위해 의존성을 모두 전달하는게 권장되고 있어요

2023-03-07 17:50 UTC, msdio commented on client/src/components/practice/long/Typing/index.tsx
> +  useEffect(() => {
여기는 호출이 굉장히 많이 되는 부분이라 `useCallback`을 사용하는건 어떨까요?

2023-03-07 17:50 UTC, msdio commented on client/src/components/practice/long/Typing/index.tsx
> +  useEffect(() => {
이거랑 이 직전의 useEffect랑 역할이 중복되는게 아닐까요..?

2023-03-07 17:50 UTC, msdio commented on client/src/utils/test/typing.test.ts
> +test('타자 정확도 계산', () => {
이렇게 같은 계열의 테스트는 describe - it 세트로 작성해주시면 테스트 결과 확인하기가 더 좋아질 것 같아요

2023-03-07 17:50 UTC, msdio commented on client/src/utils/test/char.test.ts
> +test('영어 확인', () => {
이 테스트는 굳이 필요있나 싶어요. 위의 `한글 확인`과 같은 테스트 아닐까요?

2023-03-07 17:50 UTC, msdio commented on client/src/utils/test/typing.test.ts
> +export {};
export 는 넣으신 이유를 알 수 있을까요?

2023-03-07 17:50 UTC, msdio commented on client/src/utils/char.ts
> +export const getConstantVowel = (char: string) => {
이 함수는 어떤 역할을 하고 있는 걸까요?

2023-03-07 17:50 UTC, msdio commented on client/tsconfig.json
> +    "target": "es6",
es6로 변경하신 이유가 있을까요?

2023-03-07 17:50 UTC, msdio commented on client/jest.config.js
> +  },
여기 test environment로 node를 추가해주지 않아도 잘 동작하나요..?

2023-03-08 01:54 UTC, msdio commented on client/src/utils/typing.ts
> +  if (states === 'f') return 0;
f, c대신 empty, c 대신 correct로 바꾸는건 어떨까요? 처음 봤을 때는 무슨 상태인지 확인이 힘들 것 같아요.

또 states 값은 일정한 옵션 내에서 정해지는 값이라 string이 아닌 enum 타입으로 지정해주는게 더 좋을 것 같아요!

2023-03-08 05:04 UTC, msdio commented on client/src/utils/typing.ts
> + * @param typingCount 타수
👍

2023-03-08 05:05 UTC, msdio commented on client/src/utils/typing.ts
> +export const getTypingWpm = (typingCount: number, minute: number) => {
여기 파라미터 부분은 저희 컨벤션에 따라 하나의 객체로 관리하는게 더 좋지 않을까요? 여기서 만든 타입은 아래에서도 재사용이 가능할 것 같아요.

2023-03-08 05:08 UTC, msdio commented on client/src/utils/typing.ts
> +      if (!wrongKeys[contentComponent]) wrongKeys[contentComponent] = { total: 1, count: 0 };
위처럼 단순히 `return 0;`와 같은 경우를 제외하고는 괄호로 감싸는게 어떨까요? 이에 대한 컨벤션도 정해봐야겠네요

2023-03-08 05:16 UTC, msdio commented on client/src/pages/practice/long/[typingId]/[pageNum].tsx
> +  const res: { data: LongTypingResponse } = await new Promise((resolve) => {
mock 데이터를 사용하기 위해 이렇게 작성하셨을까요?

이렇게 하면 나중에 서버와 연결할 때 코드를 다시 작성해야 할 것 같아서, mock api를 따로 만들어서, 그곳 내부에서 Promise로 리턴해주는 함수를 여기서 await로 받아서 사용하는 방식으로 작성하면 나중에 실 서버와 연결할 때는 여기 코드는 놔두고 연결만 수정해주면 될 것 같아요.

2023-03-08 05:18 UTC, msdio commented on client/src/components/practice/short/index.tsx
> +  const [currentIdx] = useState(0);
set 함수 없이 사용하는 변수들인데 굳이 state로 사용하신 이유가 있을까요?

2023-03-08 05:24 UTC, msdio reviewed
윤우님 고생하셨습니다!

저번 회의때도 나온 이야기지만, pr을 좀 쪼개서 올려주시는게 좋을 것 같아요.
이렇게 pr의 단위가 너무 커지면

```
1. 한번에 리뷰하기가 너무 힘들어요..
2. 리뷰 -> 수정 -> 머지의 주기가 너무 길어질 것 같아요.
3. 다른 팀원이 만든 코드들을 재사용하지 못하고, 다들 따로 작성하다 보니 나중에 코드 합치는 데에 공수가 너무 많이 들 것 같아요.
```

너무 하나의 기능을 다 완성한 뒤 올리기보다는.. util 함수 하나만 만들고 pr만 올리는 방식으로 하셔도 되고, 정신차려보니 이미 작업을 다 한뒤라면 파일을 좀 나눠서 pr을 올려주시면 더 좋을 것 같아요!

2023-03-08 05:26 UTC, msdio commented on client/src/components/practice/long/Layout/index.tsx
> +  background-image: linear-gradient(90deg, #fff6f1 1px, transparent 1px), linear-gradient(#fff6f1 1px, transparent 1px);
여기 부분은 제가 메인에서 사용한 부분을 가져오셨다면 더 편했을 수 있겠다는 생각이 드네요

2023-03-08 05:33 UTC, coolsmart2 commented on client/package.json
> +    "hangul-js": "^0.2.6",
한글 받침이 수미님이 만드신건 분리되지 않고 hangul-js은 분리됩니다. 그리고 임시적으로 사용하고 나중에 직접 구현하거나 할 것 같아요

2023-03-08 05:34 UTC, coolsmart2 commented on client/package.json
> +    "build": "next build",
다시 되돌려 놓겠습니다

2023-03-08 05:37 UTC, coolsmart2 commented on client/src/utils/test/char.test.ts
> +test('영어 확인', () => {
위에는 isHangulChar을 테스트한 코드고 아래는 isEngulishChar 메서드를 테스트해서 다른 테스트긴 합니다

2023-03-08 05:37 UTC, coolsmart2 commented on client/src/utils/test/typing.test.ts
> +export {};
안 넣으면 eslint에서 자꾸 위협합니다

2023-03-08 05:39 UTC, coolsmart2 commented on client/tsconfig.json
> +    "target": "es6",
변경하지 않으면 사용하려했던 [...array] 문법을 사용하지 못하고 그 이외 es6 문법 사용을 하지 못합니다

2023-03-08 05:39 UTC, coolsmart2 commented on client/jest.config.js
> +  },
일단 yarn test로 해보니까 모두 잘 동작하는 것 같습니다. 저도 node 넣는 거 봤는데 어디는 넣고 어딘 안 넣어서 그냥 빼고 테스트 했습니다

2023-03-08 05:41 UTC, coolsmart2 commented on client/src/utils/typing.ts
> +  if (states === 'f') return 0;
상태를 한 글자로 해야 의미가 있습니다. 타이핑한 문자수와 상태수는 동일하기 때문에 이후 포커싱되는 문자를 찾기 쉽습니다. 이후 type으로 만들어서 보기 편하게 만들도록 하겠습니다.

2023-03-08 05:42 UTC, coolsmart2 commented on client/src/utils/typing.ts
> + * @param typingCount 타수
테스트 코드 작성하는 거 재미없을 줄 알있는데 꽤 할만합니다 ㅋㅋ 테스트 통과하면 기분도 아주 조금이지만 좋아요

2023-03-08 05:43 UTC, coolsmart2 commented on client/src/utils/typing.ts
> +export const getTypingWpm = (typingCount: number, minute: number) => {
파라미터를 객체로 넘긴다는 생각을 미쳐하지 못했네요... 제 생각에도 객체로 파라미터를 관리하는 것이 좋을 것 같습니다.

2023-03-08 05:45 UTC, coolsmart2 commented on client/src/utils/typing.ts
> +      if (!wrongKeys[contentComponent]) wrongKeys[contentComponent] = { total: 1, count: 0 };
이건 다 괄호로 감싸는 것이 좋을 것 같네요. 괄호는 다 넣어두도록 할게요

2023-03-08 05:47 UTC, coolsmart2 commented on client/src/pages/practice/long/[typingId]/[pageNum].tsx
> +  const res: { data: LongTypingResponse } = await new Promise((resolve) => {
api 폴더에 메서드를 만들고 그 메서드를 여기로 연결시킨다는 말씀이신가요? 그게 이후 코드 작성할 때 좋을 것 같네요

2023-03-08 05:48 UTC, coolsmart2 commented on client/src/components/practice/short/index.tsx
> +  const [currentIdx] = useState(0);
short 부분은 제 파트는 아니지만 이후 사용하실려고 넣으신 거 아닐까요?

2023-03-08 05:50 UTC, coolsmart2 commented
종현님의 pr 나누라고 하셨을 때 아차 싶었는데 이미 물이 엎질러져서 죄송합니다. 그래도 코드 리뷰 꼼꼼히 해주셔서 감사합니다. 다음부터 pr 크기를 신경쓰도록 하겠습니다.

2023-03-08 10:23 UTC, coolsmart2 commented on client/src/utils/char.ts
> +export const getConstantVowel = (char: string) => {
문자를 글쇠로 분리시키는 메서드입니다. 현재 hangul-js로 대체되어 사용되고 있지 않지만 이후 개발회의에서 한글 받침에 대해 글쇠를 더 분리할 것인지 결정하면 사용할지 안할지 결정될 것 같습니다.

2023-03-08 11:06 UTC, coolsmart2 commented on client/src/components/practice/long/Typing/index.tsx
> +  useEffect(() => {
위의 useEffect는 시간이 지날때 리렌더링을 확인하는 훅이고 아래는 사용자가 타이핑을 하는 경우 리렌더링을 확인하는 훅입니다.  처음 생각은 시간에 따른 useEffect는 의존성으로 시간만 넣고 타이핑에 따른 useEffect는 의존성으로 타이핑 상태만 넣었는데 useEffect에 의존하는 모든 상태를 넣어야 경고가 사라져 다 넣다보니 비슷해져버렸습니다. 하나로 합쳐야 겠네요

2023-03-08 11:40 UTC, coolsmart2 commented on client/src/components/practice/long/Typing/index.tsx
> +  useEffect(() => {
useCallback 쓰니까 깔끔해지네요!!! 좋습니다 👍🏼

2023-03-08 11:55 UTC, coolsmart2 commented on client/src/pages/practice/long/[typingId]/[pageNum].tsx
> +  const res: { data: LongTypingResponse } = await new Promise((resolve) => {
생각해보니까 getServerSideProps는 프론트에서 axios를 사용하는 것이 아닌 서버에서 fetch를 하는 것 같은데 서버에서 사용하는 fetch도 프론트의 apis 폴더를 만든 것처럼 할까요?

2023-03-12 05:33 UTC, msdio approved these changes
export path map에 대해서는 다시 한번 이야기해봐요...

2023-03-12 05:34 UTC, merged

2023-03-16 12:30 UTC, sumi-0011 commented on client/src/utils/typing.ts
> +  if (states === 'f') return 0;
한글자로 하되, 주석을 지우고 주석에 관련된 내용은 enum이나, mapping을 이용하는게 좋을것 같아요. 
다른 사람이 보면은 무슨 변수하기 유추하기가 너무 어려운것 같습니다.