긴 글 api 연결 및 임시 페이지 이동
msdio/Tamago pull request #167
Opened 2023-03-13 07:37 UTC by coolsmart2

## 📄 구현 내용 설명
- close #156 
- 긴 글 불러오는 api 연결하여 긴 글 목록에서 제목 클릭 시 해당 글로 이동
- 해당 글이 여러 페이지로 이루어져 있다면 다음 페이지로 이동 후 사용자 통계

### ⛱️ 주요 변경 사항
- 기존 원본 글 내용과 관련 데이터를 저장해둔 변수를 상태로 변환
- router.push를 통해 다음 페이지로 이동 시 useEffect에서 사용하는 상태 모두 초기화 (이 부분때문에 변수를 상태로 바꿈)
  - 아니면 location.href을 통해 새로고침하여 이동해야 됩니다. 뭐가 맞는지 모르겠네요

### 🙋 이 부분을 리뷰해주세요
- 현재 긴 글 타이핑 관련 로직을 따로 분리하지 않았습니다.
- 위에서 말한 location.href을 사용하지 않고 router.push를 이용해 라우팅하는 경우 상태가 변하지 않는 문제(같은 동적 url일 경우에만)를 useEffect에서 초기화시켜 해결할지 아니면 location.href을 사용해 새로고침하여 컴포넌트를 새롭게 리렌더링하여 해결할지 모르겠습니다.

### 🤔 여기를 참고하면 도움이 돼요

-   [Next.js 경로 변경 시 상태 재설정
](https://www.seancdavis.com/posts/resetting-state-on-nextjs-route-change/)
-

2023-03-14 08:14 UTC, msdio commented on client/src/utils/typing.ts
> +  const minute = millisecond / 60000;
60000과 이 밑에 5 이런 숫자들은 어떤 숫자인지 작성자 외에는 알 수가 없어서, 변수로 사용하면 좋을 것 같아요.

2023-03-14 09:34 UTC, sumi-0011 requested changes

2023-03-14 09:34 UTC, sumi-0011 commented on client/src/components/practice/long/Typing/index.tsx
> +        millisecond: time.minute * 60000 + time.second * 1000 + time.ms,
이부분은 useStopwatch에서 계산해서 하는것이 좋을 것 같습니다. 
어제 잘 안된 이유는 6만으로 나누어주지 않아서 그랬던 거여서요!

2023-03-14 09:34 UTC, sumi-0011 commented on client/src/components/practice/long/Typing/index.tsx
> -  }, []);
`resetTyping`등의 이름으로 함수를 만들어서 따로 빼주는 것이 좋을 것 같습니다.

2023-03-14 09:34 UTC, sumi-0011 commented on client/src/components/practice/long/Typing/index.tsx
> +      typingInfos[value.length - 1].components = disassemble(value[value.length - 1]);
```suggestion
      typingInfos[value.length - 1] = {
      char : value[value.length - 1],
      type : getCharType(value[value.length - 1]),
      components : disassemble(value[value.length - 1])
      }
```

이와 같은 방식은 어떨까요?
직접 변경하는 방식 보다는 참조를 옮기는 방식이 좋은것으로 알고있습니다.

2023-03-14 09:34 UTC, sumi-0011 commented on client/src/utils/typing.ts
> +};
이부분은 긴글에서만 사용하는 부분인것 같은데, 긴글 안에 utils 파일을 만들어서 사용하면 좋을 것 같아요

2023-03-14 10:17 UTC, coolsmart2 commented on client/src/components/practice/long/List/index.tsx
> +                    <Link href={`${PRACTICE_LONG_PATH}/${typingId}/1?mode=practice`}>{title}</Link>
isTyping하면 실전일 경우에 경우를 만들어 낼 수 없어 mode=practice로 하고 실전은 mode=exam 이렇게할 생각이였는데 어떻게 생각하시나요?

2023-03-14 10:18 UTC, coolsmart2 commented on client/src/components/practice/long/Typing/index.tsx
> +        millisecond: time.minute * 60000 + time.second * 1000 + time.ms,
수미님 Pr 머지되면 고쳐놓을게요

2023-03-14 10:19 UTC, coolsmart2 commented on client/src/components/practice/long/Typing/index.tsx
> -  }, []);
넵 빼두도록 하겠습니다.

2023-03-14 10:21 UTC, coolsmart2 commented on client/src/components/practice/long/Typing/index.tsx
> +      typingInfos[value.length - 1].components = disassemble(value[value.length - 1]);
이 부분에 대해서 모두 useRef로 바꾼 상태 입니다.
상태가 아닌 useRef로 선언한 변수는 직접 변경하는 것이 맞겠죠?

2023-03-14 10:22 UTC, coolsmart2 commented on client/src/utils/typing.ts
> +};
넵

2023-03-14 10:46 UTC, coolsmart2 commented on client/src/pages/practice/long/[typingId]/[pageNum].tsx
> +  const res = await fetch(
통신을 하는 환경이 다를 줄 알고 일부러 fetch를 사용했는데 api 폴더에 만들어서 일단 사용해보겠습니다

2023-03-14 15:44 UTC, sumi-0011 commented on client/src/components/practice/long/Typing/index.tsx
> +      typingInfos[value.length - 1].components = disassemble(value[value.length - 1]);
앗 아니요 이건 state 관련 컨벤션이 아니고, 
자바스크립트에서 객체의 값을 변경할떄는 이런 방식을 사용해야하는 것으로 알고있는데, 정확한 이유를 아직 못찾습니다. ㅜ 
찾아보고 슬랙에 올릴게요!

2023-03-14 15:45 UTC, sumi-0011 commented on client/src/components/practice/long/Typing/index.tsx
> +      typingInfos[value.length - 1].components = disassemble(value[value.length - 1]);
@msdio 해람님은 어떻게 생각하시나요. 혹시 이유를 아시나요?

2023-03-15 12:16 UTC, msdio commented on client/src/components/practice/long/Typing/index.tsx
> +      typingInfos[value.length - 1].components = disassemble(value[value.length - 1]);
윤우님이 사용하신 방식은 `dot notation`이라고 부르고,
수미님이 제안하신 방식은 `bracket notation`이라고 불러요.

bracket notation 방식이 띄어쓰기 같은 특수문자나 숫자, 변수를 사용할 수 있어서 좀 더 자유롭다고는 알고있는데, dot notation을 사용하는 것을 지양해야 하는 이유는 저도 잘 모르겠습니다...🙄

2023-03-16 05:24 UTC, sumi-0011 commented on client/src/components/practice/long/Typing/index.tsx
> +      typingInfos[value.length - 1].components = disassemble(value[value.length - 1]);
드디어 제가 그렇게 생각한 이유를 알아냈는데, 리액트 불변성에 대한 내용이였어요. 
useState같은 경우에는 이 불변성을 지켜야 하는거 같은데, useRef를 사용할때는 리렌더링과 관계 없어 크게 상관없는것 같네요. 

useState에서는 참조값이 바뀌어야 객체가 변했다고 감지하고, 리렌더링을 시키게 되는데
useState를 사용할때 이처럼 사용하면 참조가 변하지 않았는데 객체 안의 값을 함부로 바꾸면 예상치 못한 버그가 발생할수 있고, 객체가 변경되었다고 감지 하지 못할수도 있다는 문제가 있어 새로운 객체를 생성해서 넣어주도록 하는 방식을 사용해야합니다. 

그런데 위 내용과 제 얕은 지식이 충돌해서.. 헷갈렸네요 😭

[리액트 불변성이란? ](https://hsp0418.tistory.com/171)

2023-03-16 05:25 UTC, sumi-0011 approved these changes

2023-03-17 14:54 UTC, merged