[#14] 헤더, 푸터, 회원가입 페이지 UI 구현
msdio/Tamago pull request #23
Opened 2023-02-07 18:12 UTC by coolsmart2

## 📄 구현 내용 설명
- #14 
- #21 

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/65846992/217320289-45562584-e92c-40fc-97db-937d38433b25.png">

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/65846992/217320448-657c2cee-5258-4a41-9899-67852fb3be5c.png">

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/65846992/217326740-2afee7e4-47ab-46bf-9343-8aeef7898cd6.png">

### ⛱️ 주요 변경 사항
- 메인 화면 Header와 Footer 구현
- 서비스 이용약관 페이지 ui
- 회원가입 페이지 ui
- input 컴포넌트 분리
- button 컴포넌트 분리

### 🙋 이 부분을 리뷰해주세요
- 차크라 사용에 있어서 불필요한 것들 또는 좋은 기능을 활용하지 못한 부분들
- 컴포넌트 분리의 기준을 잘 몰라 잘 나누었는지
- 서비스이용약관 페이지가 필요한지 의문이 들었습니다.
- 아직 다른 분들이 어떤 식으로 설계할지 몰라서 일단 내키는대로 구현해봤습니다. 앞으로 어떻게 설계할지 의논해보면 좋을 것 같습니다.
- 리액트 최적화 같은 부분들은 추후 더 공부해서 적용해보도록 하겠습니다.
- 상수 처리를 어떻게 해야 할지 의논해봐야 할 것 같습니다. (지금은 거의 안되어 있습니다.)

### 🤔 여기를 참고하면 도움이 돼요
-  차크라 공식 문서
-

close #21 
close #14

2023-02-08 08:38 UTC, sumi-0011 requested changes

2023-02-08 08:38 UTC, sumi-0011 commented on client/src/components/util/Checkbox.tsx
> +}
```suggestion
  return (
      <Icon viewBox='0 0 19 19' {...reset}>
          <Img src={isChecked ? 'images/checkbox_true_1.svg' : ''images/checkbox_false_1.svg''} />
      </Icon>
  );
}
```

이런식으로 안한 이유가 있는지 궁금합니다!

2023-02-08 08:38 UTC, sumi-0011 commented on client/src/components/util/InputForm.tsx
> +}
optional parameter이 젤 밑에 오도록!

```suggestion
interface InputProps {
  name: string;
  value: string;
  regex: RegExp;
  theme: FontBorderTheme;
  onChange?: (e: ChangeEvent<HTMLInputElement>) => void;
  type?: string;
  w?: string;
  h?: string;
  placeholder?: string;
  errorMessage?: string;
}
```

2023-02-08 08:38 UTC, sumi-0011 commented on client/src/components/util/SubmitButton.tsx
> +  colorScheme?: string;
여기도 위처럼 optional param이 마지막에 오게!

2023-02-08 08:38 UTC, sumi-0011 commented on client/src/components/util/SubmitButton.tsx
> +};
저희 이거 쓰나요? @msdio @coolsmart2

2023-02-08 08:38 UTC, sumi-0011 commented on client/src/constants/theme.ts
> +};
이부분은 회의때 말했던 거처럼 디자인 가이드가 나오면 차크라로 수정하는거죵?

2023-02-08 08:38 UTC, sumi-0011 commented on client/src/pages/_app.tsx
> +  },
여기 분리하고, emailButton 색 이름으로 변경하기!

2023-02-08 10:38 UTC, msdio commented on client/src/components/Header.tsx
> +  const [isLogin, setIsLogin] = useState(false);
useState 내부를 보면, 이렇게 되어 있어요.

```jsx
function useState<S>(initialState: S | (() => S)): [S, Dispatch<SetStateAction<S>>];
```

위처럼 같은 제네릭 타입을 공유하고 있어서 초기화 할때 `false`로 초기화 되면, 자동으로 boolean 타입으로 선언돼요!

2023-02-08 10:42 UTC, msdio commented on client/src/components/Header.tsx
> +              }}
저도 위로 빼서 작성하는게 가독성이 더 좋을 것 같아요!

2023-02-08 10:49 UTC, msdio commented on client/src/components/util/InputForm.tsx
> +}
이건 제가 ESLint 설정에서 만질 수 있는지 찾아볼게요!

2023-02-08 10:56 UTC, msdio requested changes
프로젝트 구조와, 리뷰된 내용들만 수정되면 좋을 것 같습니다 👍👍

2023-02-08 10:57 UTC, msdio commented
+ 컨플릭트 나는 부분도 한번 봐주세요!

2023-02-08 14:32 UTC, sumi-0011 commented on client/src/components/util/SubmitButton.tsx
> +};
회의 후, defultProps는 es6전에 사용하는 방법인것을 알게되어 
사용하지 않기로

2023-02-09 03:42 UTC, coolsmart2 commented on client/src/components/util/Checkbox.tsx
> +}
체크박스 커스텀하다가 실패한 코드라 이 파일은 삭제를 하도록 하겠습니다

2023-02-09 04:10 UTC, coolsmart2 commented on client/src/components/util/SubmitButton.tsx
> +};
default function parameter로 변경하겠습니다

2023-02-09 04:11 UTC, coolsmart2 commented on client/src/constants/theme.ts
> +};
일단 styles 폴더에 넣어두고 차크라 설정하면 삭제하도록 할게요

2023-02-09 04:13 UTC, coolsmart2 commented on client/src/pages/_app.tsx
> +  },
gray로 바꾸니까 gray가 차크라 예약어 같아서 동작을 안하는 것 같아 일단 tamago_gray로 바꾸었습니다.

2023-02-09 04:47 UTC, coolsmart2 commented on client/src/components/Header.tsx
> +              }}
일단 뺏는데 헤더, 푸터 구현하시는 분이 고쳐쓰시면 될 것 같아요.

2023-02-09 07:09 UTC, sumi-0011 approved these changes

2023-02-09 07:09 UTC, sumi-0011 commented on client/src/components/common/InputForm.tsx
> +}: InputProps) {
이부분은 디자인 시스템에 맞춰서 좀수정될거같아요! size가 다 나와서요

2023-02-09 07:09 UTC, sumi-0011 commented on client/src/pages/_app.tsx
> +    },
이부분도 디자인 시스템에 secondary 컬러로 변경하면 될것같아요!

2023-02-09 07:24 UTC, msdio approved these changes
👍

2023-02-09 07:24 UTC, merged