[#30] design system setting
msdio/Tamago pull request #33
Opened 2023-02-10 06:02 UTC by sumi-0011

## 📄 구현 내용 설명
디자인 시스템 프론트 세팅 - chakra theme
### ⛱️ 주요 변경 사항
- custom button 생성
- theme 파일 분리
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/49177223/218014777-9d3819c7-5806-460c-8da2-e473b01f9ef3.png">
- 해당 브랜치의 /designSystem 경로를 들어가면 구현된 버튼을 확인 할 수 있습니다.
### 🙋 이 부분을 리뷰해주세요
- button custom 을 구현했는데, 괜찮은지 확인해주세요!
-

### 🤔 여기를 참고하면 도움이 돼요

- [adding-a-custom-variant](https://chakra-ui.com/docs/components/tag/theming#adding-a-custom-variant)
- [component-style] (https://chakra-ui.com/docs/styled-system/component-style)

2023-02-10 07:56 UTC, coolsmart2 requested changes

2023-02-10 07:56 UTC, coolsmart2 commented on yarn.lock
> +
yarn.lock, .gitignore에 node_module 삭제해주세요~!!

2023-02-10 08:33 UTC, msdio commented on yarn.lock
> +
아마 최상위 디렉토리에 실수로 모듈을 설치하신게 아닐까요..? 한번 확인해주셔요

2023-02-10 09:16 UTC, msdio commented on client/src/styles/Button.ts
> +const basicVariant = defineStyle((props) => {
내부에 컬러 세팅들만 있는 것 같아서, colorVariant로 네이밍을 변경하는 건 어떨까요?

2023-02-10 09:18 UTC, msdio commented on client/src/styles/Button.ts
> +const basicVariant = defineStyle((props) => {
outline을 outlineVariant로 설정하신 것 처럼, 여기도 네이밍을 속성 이름과 맞춰서 `baseVariant`로 변경하는 건 어떨까요?

2023-02-10 10:30 UTC, msdio reviewed
디자인 시스템 관련해서 폴더 구조를 좀 잡고 가면 좋을 것 같아요!
지금은 확장성이 많이 떨어지는 구조라고 생각해서, 나중에 컴포넌트들이 많이 추가되면 디렉토리 가독성이 많이 떨어질 것 같아요.

저도 구조를 어떻게 짜야할지 고민이 많이 돼서 깃허브에 같은 스택을 사용하는 프로젝트들을 많이 뒤져봤는데, 제가 생각하는 것들을 정리해볼 테니 의견 남겨주세요!

### 1. `designSystem.tsx`에 모든 버튼들을 모아놓은 이유가 있을까요?
나중에 다른 컴포넌트(인풋, 차트, ...)들이 추가되면, 가독성이 많이 떨어질 것 같다는 생각이 들어요. 지금 아예 종류별로 컴포넌트를 나눠 놓으면 더 좋지 않을까요?

제가 제안하고 싶은 방법은 
> 1. `styles` 폴더 안에 `components`나 `design-system`과 같은 폴더를 만들어서 해당 폴더에 디자인 시스템 관련된 컴포넌트들을 모아놓기
> 2. `styles` 폴더와 같은 레벨에 `theme`폴더를 만들어서 거기에 차크라 관련 컴포넌트들을 모아놓기
> 3. 기존에 존재하는 `components`폴더에 `@styles`와 같은 폴더를 추가해서 컴포넌트들을 모아놓기

이 정도인데, 다른 방법이 있다면 의견 주세요!

### 2. `designSystem.tsx` 파일의 위치와 내용
#### 1) 파일 내용
우선 'designSystem'과 같은 제너럴한 이름을 사용하신 이유가 궁금해요. 나중에 다른 컴포넌트들이 추가되면 다 한 파일에 모아놓으려고 하신걸까요? 만약 그렇다면, 해당 방식의 장점이 궁금합니다!

#### 2) 파일 위치
pages 폴더 안에 놓으신 이유가 궁금해요. 만약에 눈으로 확인하기 위한 용도라면, 저희가 UI testing 도구로 storybook을 사용하기 때문에 스토리 파일을 작성해서 컴포넌트를 관리하는게 더 좋아 보여요.

1번에서 스타일링 폴더들의 위치와 비슷하게 컴포넌트 별로 폴더를 분리해서 작성하는게 나중에 유지보수에 더 좋지 않을까요?

cf) 지금은 버튼 컴포넌트의 이름들이 다 `Button`으로 되어있는데, 나중에 사용할 때는 아래와 같이 작성하면 될까요?
```jsx
<Button size='lg' ... >{someText}<Button/>
```
만약에 위와 같이 사용하는게 아니라면, 미리 위와 같은 버튼을 `ButtonLarge`와 같은 네이밍으로 따로 커스텀 해서 나중에 `ButtonLarge`를 import 해서 사용하는 방법은 어떻게 생각하실까요?

다음에 다른 곳에서 사용할 가능성이 있는 코드를 작성하신다면, 어떻게 사용해야 하는지 사용법을 간단하게 작성해주시면 한번 리뷰가 끝난 파일을 매번 읽지 않아도 돼서 서로 더 도움이 될 것 같아요.

### 3. designSystem.tsx 파일의 sm 사이즈 버튼
```jsx
<Button size='sm' colorScheme='secondary' variant='outline'>
    Check _ sm{' '}
</Button>
```
다른 버튼들과 달리, 마지막에 `{' '}`을 작성하신 이유가 있을까요?

### 4. `theme.ts` 파일 안의 colors 주석
100 - 700까지의 설명을 상세하게 적어주셔서 나중에 사용할 때 바로 확인이 가능해서 좋을 것 같아요!

1. 설명이 비어있는 값들은 사용하지 않기 때문에 비워놓으신 걸까요?
2. 맨 위에 존재하는 주석들 외에 아래 사진처럼 라인별 추가 주석들은 작성하신 이유가 궁금합니다.
<img width="250" alt="Screenshot 2023-02-10 at 7 22 00 PM" src="https://user-images.githubusercontent.com/59170680/218067601-76cf1d63-8ef8-4ef1-ab39-bd6a7d483f3c.png">

<br/>

긴 리뷰 읽느라 고생하셨습니다!
우선 보이는 건 이정도인데,, 제가 정답이 아니라 의견을 제시한 것이기 때문에 같이 고민해보면서 수정해보면 좋을 것 같아요! 추가적으로 생각나는게 있다면 남겨놓을게요 :)

2023-02-10 14:59 UTC, sumi-0011 commented on yarn.lock
> +
네넵

2023-02-10 14:59 UTC, sumi-0011 commented on client/src/styles/Button.ts
> +const basicVariant = defineStyle((props) => {
아 그러네요, 감사합니다!

2023-02-10 15:14 UTC, sumi-0011 commented
@msdio 

1-2. designSystem.tsx 
1) 파일내용
단순히 디자인 시스템 요소들을 구현해놓고, 확인하기 위한 용도라 제네럴한 이름을 사용했어요. 
올릴때 지울까 하다가, 구현 된 버튼들을 한번 확인하셔도 좋을것이라고 생각해 지우지 않고 올렸습니다. 
추후에는 지우면 될 것 같아요
2) 파일 위치
넵 저도 스토리북으로 사용하는게 좋다고 생각해요, 그런데 이 파일은 제가 테스트 하기 위한 용도여서, 장점이라고 한다면 아직 스토리북을 써보지 않은 제가 확인하기 쉽다 정도..? ㅎㅎ

실제로 커스텀 버튼이 구현된 부분은 styles/buttun.ts 입니다. 이걸 테스트 하기 위해 페이지를 만든것이구요, 
말하신것과 같이 Button 이라고 사용하면 되는데, 이게 가능한 이유가
제가 chakra ui에 존재하는 button 컴포넌트의 기본theme을 저희에 맞게 수정한 것이라서, chakra ui button 사용하는 방식처럼 사용하시면 되요, 
대신 size=lg 인 경우 등등에 width가 chakra와는 다르고 저희 디자인 시스템에 맞춰져 있다는점!
따라서 ButtonLarge와 같은 컴포넌트는 만들 필요가 없다고 생각합니다. 
3. designSystem.tsx 파일의 sm 사이즈 버튼
이건 실수예요.. 수정하겠습니다.

4. theme.ts 파일 안의 colors 주석
1) 설명이 비어있는 값은, 제가 임의로 정해둔 색이다 + 사용하지 않는 색이라 정해진 색이 없는 부분입니다. 
2) 이 코드 자체가 완성본이 아니고, 중간 점검을 받기 위해서 풀리퀘를 올린거라 자잘한 실수 들이 있네요, 딱히 의미는 없다고 보시면 되요😓

자세한 의견 감사합니다!
다음에는 오해되는 부분이 없게 더 상세하게 설명하고,전달할수 있도록 하겠습니다.

2023-02-11 09:35 UTC, coolsmart2 approved these changes

2023-02-11 09:58 UTC, coolsmart2 commented
두 분이 이야기 나눈 것을 보고 정리를 해봤는데 해람님은 아래와 같은 코드에서 before같은 코드를 많이 사용할 것 같으니 after로 랩핑하여 쓰기 편하게 하는 게 좋은 것 같다고 하신 것 같고
수미님은 `size='lg'`만 props로 넣어주기만 하더라도 다른 스타일 관련된 props를 넣어주지 않더라도 차크라에 우리가 지정해준 스타일가 자동으로 적용되기 때문에 상관없다고 하신 것이 같은데 이렇게 이해하면 되는 것일 까요?
```JavaScript
<Button size='lg' ... >{someText}<Button/> // before

<ButtonLarge>{someText}</ButtonLarge> // after
```

2023-02-11 10:43 UTC, msdio commented
> 두 분이 이야기 나눈 것을 보고 정리를 해봤는데 해람님은 아래와 같은 코드에서 before같은 코드를 많이 사용할 것 같으니 after로 랩핑하여 쓰기 편하게 하는 게 좋은 것 같다고 하신 것 같고 수미님은 `size='lg'`만 props로 넣어주기만 하더라도 다른 스타일 관련된 props를 넣어주지 않더라도 차크라에 우리가 지정해준 스타일가 자동으로 적용되기 때문에 상관없다고 하신 것이 같은데 이렇게 이해하면 되는 것일 까요?
> 
> ```js
> <Button size='lg' ... >{someText}<Button/> // before
> 
> <ButtonLarge>{someText}</ButtonLarge> // after
> ```

넵 이해하신게 정확한데, 저도 수미님이 designSystem.tsx 파일에 디자인된 컴포넌트들을 미리 다 정의해놓은 뒤,
나중에 사용할 때는 해당 파일에서 import 해서 사용하려는 의도로 이해해서 저렇게 제안한 거였어요.

그런데 그렇게 사용하는게 굳이 한번 더 감싸게 되는 것 같아서, 저도 버튼과 같은 단순한 컴포넌트는 그냥 before처럼 사용하는게 좋아보입니다!

2023-02-11 10:44 UTC, merged